class BoardOutException(Exception): ...
class IncorrectShipPlacement(Exception): ...
class IncorrectShipDirection(Exception): ...
class IncorrectShotPoint(Exception): ...
class BoardCreatingError(Exception): ...